nome = str(input("Digite seu nome completo: ")).strip()
nomeDividido = nome.split()
print("Muito prazer em te conhecer!")
print("Seu primeiro nome é {}".format(nomeDividido[0]))
print("Seu último nome é {}".format(nomeDividido[-1]))
